import json
import os
import time

from dotenv import load_dotenv
from google import genai

from app.schemas import NewsComicPageScript


load_dotenv()

API_KEY = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=API_KEY)

PRIMARY_TEXT_MODEL = os.getenv("GEMINI_TEXT_MODEL", "gemini-2.5-flash")
TEXT_MODELS = list(dict.fromkeys([
    PRIMARY_TEXT_MODEL,
    "gemini-2.5-flash-lite",
]))

MAX_RETRIES_PER_MODEL = 3


def clean_json(text: str) -> str:
    text = text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "", 1).strip()
    if text.startswith("```"):
        text = text.replace("```", "", 1).strip()
    if text.endswith("```"):
        text = text[:-3].strip()

    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]

    return text


def generate_json(prompt: str) -> dict:
    last_error = None

    for model_name in TEXT_MODELS:
        for retry in range(MAX_RETRIES_PER_MODEL):
            try:
                response = client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                )
                return json.loads(clean_json(response.text or ""))
            except Exception as e:
                print(f"Gemini text generation failed: {model_name}")
                print(e)
                last_error = e
                time.sleep(2 + retry)

    raise RuntimeError(f"Gemini text generation failed after fallback models: {last_error}")


def generate_news_comic_page_script(article_text: str) -> NewsComicPageScript:
    prompt = f"""
You are a Traditional Chinese news comic infographic planner.

Read the news article and create a complete one-page news manga infographic
script. The final image will be generated by Gemini Image / Nano Banana in one
single image, so you must plan the whole page, panel count, panel titles,
short quote lines, callouts, and visual scenes.

Return ONLY valid JSON. Do not use Markdown fences.

Important:
- The news topic is not fixed. It may be politics, society, campus, technology,
  culture, sports, business, disaster, entertainment, international, health, or
  other.
- First infer the news_type, story_shape, tone, attention/risk level, and best panel_count.
- Prefer a dense "news guide" infographic structure like a social media news
  explainer: headline, news category, tone, attention/risk level, summary, then
  panel-by-panel evidence and reactions.
- Prefer 6 panels for complex news with multiple actors, timeline, numbers,
  institutional response, public reaction, risk, or consequences. Use 5 panels
  for normal news with event, cause, response, and next step. Use 4 panels only
  for very simple event news.
- Build allowed_facts first. Include only article-supported names, groups,
  organizations, numbers, dates, places, and outcomes.
- Build locked_text_blocks from those facts. These are the exact short text
  blocks that should appear in the image.
- Use Traditional Chinese for all text.
- Keep every text short and suitable for a readable news comic.
- Preserve the article's core issue. Do not shift the focus toward behind-the-scenes
  trivia, celebrity gossip, sequel speculation, or unrelated production news unless
  the article itself is about those points.
- For any article, make the page explain the core news question: what happened,
  why it matters, who is involved, what evidence or numbers are known, what
  authorities or stakeholders said, and what happens next.
- For controversy/crisis articles, include anger, apology, investigation,
  government response, compensation, petitions, or accountability only when the
  article supports those facts.
- For achievement/human-interest/trend articles, include the breakthrough,
  reason, impact, beneficiary, expert view, and next step instead of forcing
  anger or crisis framing.
- Write header-style labels similar to: 新聞指南, 新聞類型, 言調, 關注等級.
  These words do not need to be separate JSON fields; express them through
  title, news_type, tone, summary, panel_title, main_text, and locked_text_blocks.
- Also write visual_prompt_en fields in precise natural English for Stable
  Diffusion 3.5. These English prompts are for illustration only, not text.
- Use cautious wording for allegations, disputes, unresolved claims, legal,
  financial, medical, or political issues.
- Do not invent brands, people, numbers, or consequences not supported by the article.
- Avoid asking for a generic four-panel story. This is a news explainer comic page.

Panel planning rules:
- panel_title: 2 to 6 Chinese characters, matched to the article shape. Examples:
  事件爆發, 關鍵背景, 爭議焦點, 官方回應, 專家看法, 民眾反應, 後續觀察, 成果亮點, 影響擴散.
- visual: concrete visual description for the illustration.
- visual_prompt_en: one detailed English sentence for Stable Diffusion 3.5.
  Use this structure: subject, action/state, environment/background,
  lighting/camera, style/quality. Do not mention speech bubbles, title bars,
  caption boxes, labels, readable text, Chinese, Japanese, English letters, or
  numbers. If the scene needs screens, phones, papers, signs, posters, uniforms,
  or documents, describe them as blank or abstract props with no markings.
  Include concrete visual details such as clothing, gestures, facial expressions,
  room or street depth, background props, material textures, and lighting mood.
  Prefer medium shots and wide shots over close-up portraits.
- characters: visible people or groups in the panel.
- main_text: the most important readable text in that panel, 10 to 24 Chinese characters.
- speech: 0 to 2 short quote or narration lines, 6 to 16 Chinese characters each.
  This will be appended to the top narration bar, not drawn as a speech bubble.
- callouts: 0 to 3 short labels or annotation boxes, 4 to 14 Chinese characters each.
- Every panel_title, main_text, speech line, and callout must also appear in
  locked_text_blocks exactly.
- Keep the whole page text short. Prefer fewer readable words over many tiny labels.
  Use short blocks, but include enough concrete names, amounts, petition counts,
  institutions, and responses to preserve the news.
- Use punchy newspaper-style wording that matches the article. Good generic
  examples: 關鍵轉折, 官方回應, 專家示警, 民眾關注, 數據曝光, 影響擴大,
  後續待觀察, 政策上路, 產業震盪, 社會共鳴.

Return this exact JSON shape:
{{
  "title": "新聞主題精準標題",
  "news_type": "政治／社會／文化／娛樂／健康／財經／國際／科技等",
  "story_shape": "conflict | achievement | accident | policy_change | investigation | human_interest | announcement | crisis | trend | other",
  "tone": "嚴肅／警示／溫暖／理性／懸疑／樂觀",
  "panel_count": 6,
  "visual_prompt_en": "A square Traditional Chinese current-affairs news guide manga infographic with six panels, bold black panel borders, headline area, category badges, article-specific scenes, stakeholders, evidence, response, and next-step visuals.",
  "summary": "用一句話說明文章核心事件、原因、影響與後續。",
  "allowed_facts": ["文章支持的人物或機構", "重要數字或日期", "核心事件", "回應或後續"],
  "locked_text_blocks": ["事件爆發", "關鍵背景", "官方回應", "民眾反應", "後續觀察", "重要數字"],
  "panels": [
    {{
      "panel_id": 1,
      "visual_prompt_en": "A clear article-specific news scene showing the main event and key stakeholders, wide editorial manga panel, no readable text inside props.",
      "panel_title": "事件爆發",
      "visual": "文章核心事件的具體可畫場景",
      "characters": ["主要人物或群體"],
      "main_text": "文章核心事件短句",
      "speech": ["關鍵說法或反應"],
      "callouts": ["重要數字", "關鍵標籤"]
    }}
  ]
}}

News article:
{article_text}
"""

    data = generate_json(prompt)
    return NewsComicPageScript.model_validate(data)


def generate_sample_article() -> dict:
    prompt = """
Create ONE fresh short Traditional Chinese sample article for testing a news-to-comic generator.
Return ONLY valid JSON with this shape:
{
  "title": "Traditional Chinese sample title",
  "article": "Traditional Chinese sample article text"
}
The article should be 180 to 260 Chinese characters and suitable for students.
"""
    return generate_json(prompt)


def generate_article_from_google_news_digest(title: str, source: str, digest: str) -> dict:
    prompt = f"""
You are a Traditional Chinese news editor.

Rewrite this Google News focus digest into ONE clean short news article for a
student news-to-comic generator.

Return ONLY valid JSON. Do not use Markdown fences.

Rules:
- Use Traditional Chinese.
- The article must be 160 to 260 Chinese characters.
- Write like a normal news article, not a list.
- Do not include metadata labels such as 來源, 發布時間, 相關報導, Google 新聞, RSS.
- Do not invent facts beyond the headline and digest.
- If the digest only contains related headlines, cautiously phrase it as
  "多家媒體報導指出..." or "報導聚焦...".
- Keep allegations, disputes, legal, financial, medical, and political topics cautious.

Return this exact JSON shape:
{{
  "title": "整理後新聞標題",
  "article": "整理後新聞正文"
}}

Main headline:
{title}

Primary source:
{source}

Digest:
{digest}
"""
    return generate_json(prompt)
