import json
import os
import time

from dotenv import load_dotenv
from google import genai

from app.schemas import NewsComicPageScript


load_dotenv()

API_KEY = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=API_KEY)

PRIMARY_TEXT_MODEL = os.getenv("GEMINI_TEXT_MODEL", "gemini-2.5-flash")
TEXT_MODELS = list(dict.fromkeys([
    PRIMARY_TEXT_MODEL,
    "gemini-2.5-flash-lite",
]))

MAX_RETRIES_PER_MODEL = 3


def clean_json(text: str) -> str:
    text = text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "", 1).strip()
    if text.startswith("```"):
        text = text.replace("```", "", 1).strip()
    if text.endswith("```"):
        text = text[:-3].strip()

    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]

    return text


def generate_json(prompt: str) -> dict:
    last_error = None

    for model_name in TEXT_MODELS:
        for retry in range(MAX_RETRIES_PER_MODEL):
            try:
                response = client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                )
                return json.loads(clean_json(response.text or ""))
            except Exception as e:
                print(f"Gemini text generation failed: {model_name}")
                print(e)
                last_error = e
                time.sleep(2 + retry)

    raise RuntimeError(f"Gemini text generation failed after fallback models: {last_error}")


def generate_news_comic_page_script(article_text: str) -> NewsComicPageScript:
    prompt = f"""
You are a Traditional Chinese news comic infographic planner.

Read the news article and create a complete one-page news manga infographic
script. The final image will be generated by Gemini Image / Nano Banana in one
single image, so you must plan the whole page, panel count, panel titles,
speech bubbles, callouts, and visual scenes.

Return ONLY valid JSON. Do not use Markdown fences.

Important:
- The news topic is not fixed. It may be politics, society, campus, technology,
  culture, sports, business, disaster, entertainment, international, health, or
  other.
- First infer the news_type, story_shape, tone, and best panel_count.
- Choose 4 to 6 panels based on article complexity:
  * 4 panels: simple event with one cause and one result.
  * 5 panels: normal news with conflict, reaction, response, and next step.
  * 6 panels: complex news with multiple actors, numbers, timeline, or consequences.
- Build allowed_facts first. Include only article-supported names, groups,
  organizations, numbers, dates, places, and outcomes.
- Build locked_text_blocks from those facts. These are the exact short text
  blocks that should appear in the image.
- Use Traditional Chinese for all text.
- Keep every text short and suitable for a readable news comic.
- Use cautious wording for allegations, disputes, unresolved claims, legal,
  financial, medical, or political issues.
- Do not invent brands, people, numbers, or consequences not supported by the article.
- Avoid asking for a generic four-panel story. This is a news explainer comic page.

Panel planning rules:
- panel_title: 2 to 6 Chinese characters, like 事件爆發, 爭議焦點, 各方回應, 後續待定.
- visual: concrete visual description for the illustration.
- characters: visible people or groups in the panel.
- main_text: the most important readable text in that panel, 10 to 22 Chinese characters.
- speech: 0 to 1 short speech bubble line, 6 to 14 Chinese characters.
- callouts: 0 to 2 short labels or annotation boxes, 4 to 12 Chinese characters each.
- Every panel_title, main_text, speech line, and callout must also appear in
  locked_text_blocks exactly.
- Keep the whole page text short. Prefer fewer readable words over many tiny labels.

Return this exact JSON shape:
{{
  "title": "新聞漫畫標題",
  "news_type": "新聞類型",
  "story_shape": "conflict | achievement | accident | policy_change | investigation | human_interest | announcement | crisis | trend | other",
  "tone": "整體語氣",
  "panel_count": 5,
  "summary": "一句話摘要",
  "allowed_facts": ["人物或機構", "重要數字", "文章支持的事件"],
  "locked_text_blocks": ["事件爆發", "短重點文字", "短對話", "短註解"],
  "panels": [
    {{
      "panel_id": 1,
      "panel_title": "事件爆發",
      "visual": "具體可畫的新聞場景",
      "characters": ["角色或群體"],
      "main_text": "短重點文字",
      "speech": ["短對話"],
      "callouts": ["短註解"]
    }}
  ]
}}

News article:
{article_text}
"""

    data = generate_json(prompt)
    return NewsComicPageScript.model_validate(data)


def generate_sample_article() -> dict:
    prompt = """
Create ONE fresh short Traditional Chinese sample article for testing a news-to-comic generator.
Return ONLY valid JSON with this shape:
{
  "title": "Traditional Chinese sample title",
  "article": "Traditional Chinese sample article text"
}
The article should be 180 to 260 Chinese characters and suitable for students.
"""
    return generate_json(prompt)
